apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ include "common.namespace" . }}
  name: {{ .Values.ingress.name }}
  annotations:
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.annotations.scheme }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.annotations.targetType }}
    alb.ingress.kubernetes.io/listen-ports: '{{ toJson .Values.ingress.annotations.listenPorts }}'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.annotations.certificateArn }}
    alb.ingress.kubernetes.io/ssl-redirect: '{{ .Values.ingress.annotations.sslRedirect }}'
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  {{- range .Values.ingress.rules }}
    - host: {{ .host }}
      http:
        paths:
        - path: {{ .path }}
          pathType: {{ .pathType }}
          backend:
            service:
              name: {{ .service.name }}
              port:
                number: {{ .service.port }}
  {{- end }}