image:
  repository: 017820660901.dkr.ecr.ap-northeast-2.amazonaws.com/user-front
  tag: latest
  imagePullPolicy: Always

deployment:
  name: user-front-deployment
  replicas: 1
  containerPort: 80

service:
  name: user-front-service
  port: 80
  targetPort: 80
  type: NodePort