namespace: test-0923

deployment:
  name: user-front-deployment
  replicas: 1
  image: 017820660901.dkr.ecr.ap-northeast-2.amazonaws.com/user-front:latest
  imagePullPolicy: Always
  containerPort: 80

service:
  name: user-front-service
  port: 80
  targetPort: 80
  type: NodePort