apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-front
  template:
    metadata:
      labels:
        app: user-front
    spec:
      containers:
        - name: user-front
          image: <ECR user-frontend>:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user-front-service
spec:
  selector:
    app: user-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80