apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "common.namespace" . }}
  name: {{ .Values.service.name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Values.deployment.name }}